"""Initial schema

Revision ID: 893a09ca3205
Revises: 
Create Date: 2025-12-27 12:21:59.380907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '893a09ca3205'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_actions',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_actions_date'), 'corporate_actions', ['date'], unique=False)
    op.create_index(op.f('ix_corporate_actions_symbol'), 'corporate_actions', ['symbol'], unique=False)
    op.create_table('holdings',
    sa.Column('portfolio_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrument_info',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('asset_class', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('market_breadth',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_breadth_date'), 'market_breadth', ['date'], unique=False)
    op.create_table('market_sentiment',
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('sentiment_magnitude', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_sentiment_date'), 'market_sentiment', ['date'], unique=False)
    op.create_index(op.f('ix_market_sentiment_symbol'), 'market_sentiment', ['symbol'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=True),
    sa.Column('qty', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('portfolio_state',
    sa.Column('portfolio_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('nav', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cash', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('gross_exposure', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('net_exposure', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('drawdown', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('high_water_mark', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices_daily',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_prices_daily_symbol_date')
    )
    op.create_index(op.f('ix_prices_daily_date'), 'prices_daily', ['date'], unique=False)
    op.create_index(op.f('ix_prices_daily_symbol'), 'prices_daily', ['symbol'], unique=False)
    op.create_table('prices_intraday',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('open', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timestamp', 'interval', name='uq_prices_intraday_symbol_ts_interval')
    )
    op.create_index(op.f('ix_prices_intraday_symbol'), 'prices_intraday', ['symbol'], unique=False)
    op.create_index(op.f('ix_prices_intraday_timestamp'), 'prices_intraday', ['timestamp'], unique=False)
    op.create_table('signals',
    sa.Column('strategy_version', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('lookback_return', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('ewma_vol', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('direction', sa.SmallInteger(), nullable=True),
    sa.Column('target_weight', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_version', 'symbol', 'date', name='uq_signals_strat_sym_date')
    )
    op.create_index(op.f('ix_signals_date'), 'signals', ['date'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_table('target_exposures',
    sa.Column('portfolio_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('target_exposure', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('scaling_factor', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_capped', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'symbol', 'date', name='uq_target_exposures_port_sym_date')
    )
    op.create_table('fills',
    sa.Column('fill_id', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('commission', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fills')
    op.drop_table('target_exposures')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_date'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_prices_intraday_timestamp'), table_name='prices_intraday')
    op.drop_index(op.f('ix_prices_intraday_symbol'), table_name='prices_intraday')
    op.drop_table('prices_intraday')
    op.drop_index(op.f('ix_prices_daily_symbol'), table_name='prices_daily')
    op.drop_index(op.f('ix_prices_daily_date'), table_name='prices_daily')
    op.drop_table('prices_daily')
    op.drop_table('portfolio_state')
    op.drop_table('orders')
    op.drop_index(op.f('ix_market_sentiment_symbol'), table_name='market_sentiment')
    op.drop_index(op.f('ix_market_sentiment_date'), table_name='market_sentiment')
    op.drop_table('market_sentiment')
    op.drop_index(op.f('ix_market_breadth_date'), table_name='market_breadth')
    op.drop_table('market_breadth')
    op.drop_table('instrument_info')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_corporate_actions_symbol'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_date'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    # ### end Alembic commands ###
